version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
#      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000


#  http://localhost:9090/graph
#  http://localhost:9090/targets
#  http://localhost:8091/actuator
#  http://localhost:8091/actuator/prometheus
#  http://localhost:8091/rest/demo
#  http://localhost:8091/rest/demo2
#  http://localhost:3000/